version: "3"
services:
  app:
    image: node:14-alpine3.16
    container_name: toolbox-challenge-server
    build: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOST=localhost
      - PORT=3000